Esmt 68/forms
esmart-eng/rasa-sam pull request #1
Opened 2021-11-22 11:38 UTC by joaomarco18

2021-11-22 11:47 UTC, pedro-campos-esmart requested changes

2021-11-22 11:47 UTC, pedro-campos-esmart commented on src/services/db/models/field_options.py
> +
Mover para a classe base. use o self.columns para obter o nome e valor de todas as colunas.

2021-11-22 11:47 UTC, pedro-campos-esmart commented on src/services/db/models/field_options.py
> +
mover para a classe base

2021-11-22 11:47 UTC, pedro-campos-esmart commented on src/services/db/models/field_options.py
> +
Crie uma classe derivada da Base, e utilize-a em toda a aplicação.

2021-11-23 11:17 UTC, joaomarco18 commented
Changes are done

2021-11-23 11:23 UTC, pedro-campos-esmart requested changes

2021-11-23 11:23 UTC, pedro-campos-esmart commented on src/services/db/models/BaseModel.py
> +        return self.__table__.columns
Usa um print iterando pelas colunas e valores, como faz com o json

2021-11-24 19:18 UTC, joaomarco18 commented on src/services/db/models/BaseModel.py
> +        return self.__table__.columns
Done

2021-11-24 19:25 UTC, merged